-- Street View geometry catalog schema.
-- Schema version: 0.5.0

CREATE TABLE catalog_meta (
    key TEXT PRIMARY KEY,
    value TEXT
);

CREATE TABLE spatial_runs (
    site_id TEXT,
    run_id TEXT,
    workspace_id TEXT,
    run_dir TEXT,
    source_url TEXT,
    reference_panoid TEXT,
    reference_lat DOUBLE,
    reference_lng DOUBLE,
    pano_count INTEGER,
    total_points BIGINT,
    distance_policy TEXT
);

CREATE TABLE raw_assets (
    asset_id TEXT,
    stage TEXT,
    site_id TEXT,
    run_id TEXT,
    workspace_id TEXT,
    anchor_panoid TEXT,
    stack_id TEXT,
    panoid TEXT,
    asset_type TEXT,
    relative_path TEXT,
    bytes BIGINT,
    sha256 TEXT,
    source_url TEXT,
    created_at TEXT
);

CREATE TABLE temporal_batches (
    site_id TEXT,
    run_id TEXT,
    workspace_id TEXT,
    batch_id TEXT,
    batch_dir TEXT,
    manifest_path TEXT,
    started_at TEXT,
    finished_at TEXT,
    target_count INTEGER,
    ok_count INTEGER,
    skipped_existing_count INTEGER,
    no_timeline_captures_count INTEGER,
    failed_count INTEGER,
    timeline_captures INTEGER,
    photometa_count INTEGER,
    strategy_json TEXT
);

CREATE TABLE pano_observations (
    site_id TEXT,
    run_id TEXT,
    workspace_id TEXT,
    panoid TEXT,
    pano_idx INTEGER,
    lat DOUBLE,
    lng DOUBLE,
    east_m DOUBLE,
    north_m DOUBLE,
    up_m DOUBLE,
    is_reference BOOLEAN,
    n_planes INTEGER,
    n_points BIGINT,
    effective_max_distance_m DOUBLE,
    b2_unique_ids TEXT,
    panorama_path TEXT,
    photometa_path TEXT,
    parsed_path TEXT,
    pointcloud_meta_path TEXT
);

CREATE TABLE visible_pois (
    site_id TEXT,
    run_id TEXT,
    workspace_id TEXT,
    panoid TEXT,
    poi_ref_type TEXT,
    place_id TEXT,
    ftid_0 TEXT,
    ftid_1 TEXT,
    name TEXT,
    category TEXT,
    icon_url TEXT,
    source_index INTEGER,
    source_field TEXT
);

CREATE TABLE b2_regions (
    workspace_id TEXT,
    site_id TEXT,
    run_id TEXT,
    panoid TEXT,
    b2_id INTEGER,
    cell_count BIGINT,
    centroid_col DOUBLE,
    centroid_row DOUBLE,
    centroid_heading_deg DOUBLE,
    target_panoid TEXT,
    target_east_m DOUBLE,
    target_north_m DOUBLE,
    target_heading_deg DOUBLE,
    target_distance_m DOUBLE,
    target_error_deg DOUBLE,
    mapping_method TEXT,
    b2_grid_path TEXT,
    parsed_path TEXT
);

CREATE TABLE tile_requests (
    site_id TEXT,
    run_id TEXT,
    workspace_id TEXT,
    panoid TEXT,
    zoom INTEGER,
    x INTEGER,
    y INTEGER,
    url TEXT,
    cb_client TEXT,
    nbt TEXT,
    fover TEXT
);

CREATE TABLE parsed_photometa (
    site_id TEXT,
    run_id TEXT,
    workspace_id TEXT,
    panoid TEXT,
    parsed_path TEXT,
    planes_path TEXT,
    indexmap_path TEXT,
    depthmap_path TEXT,
    b2_grid_path TEXT,
    n_planes INTEGER,
    map_width INTEGER,
    map_height INTEGER,
    has_indexmap BOOLEAN,
    has_depthmap BOOLEAN,
    has_b2 BOOLEAN,
    heading_deg DOUBLE,
    pitch_deg DOUBLE,
    roll_deg DOUBLE,
    capture_year INTEGER,
    capture_month INTEGER
);

CREATE TABLE indexmap_rectification (
    workspace_id TEXT,
    site_id TEXT,
    run_id TEXT,
    panoid TEXT,
    kept BOOLEAN,
    reason TEXT,
    n_planes INTEGER,
    pitch_off_deg DOUBLE,
    roll_deg DOUBLE,
    horizon_amp_local_px DOUBLE,
    horizon_amp_gravity_px DOUBLE,
    shift_px INTEGER,
    align_score DOUBLE,
    zero_shift_score DOUBLE,
    n_edge_pixels INTEGER,
    edge_shift_px INTEGER,
    edge_align_score DOUBLE,
    sky_shift_px INTEGER,
    sky_corr_strength DOUBLE,
    method TEXT,
    local_indexmap_path TEXT,
    gravity_indexmap_path TEXT,
    compare_path TEXT,
    with_pano_path TEXT,
    overlay_path TEXT
);

CREATE TABLE plane_observations (
    workspace_id TEXT,
    site_id TEXT,
    run_id TEXT,
    panoid TEXT,
    local_plane_id INTEGER,
    n_pixels BIGINT,
    class TEXT,
    local_nx DOUBLE,
    local_ny DOUBLE,
    local_nz DOUBLE,
    local_d DOUBLE,
    world_nx DOUBLE,
    world_ny DOUBLE,
    world_nz DOUBLE,
    world_d DOUBLE,
    heading_deg DOUBLE,
    pitch_deg DOUBLE,
    pitch_off_deg DOUBLE,
    roll_deg DOUBLE,
    source_json_path TEXT
);

CREATE TABLE global_factors (
    workspace_id TEXT,
    gid INTEGER,
    class TEXT,
    quality TEXT,
    nx DOUBLE,
    ny DOUBLE,
    nz DOUBLE,
    d_global DOUBLE,
    n_sources INTEGER,
    n_unique_panos INTEGER,
    total_pixels BIGINT,
    normal_consistency_min DOUBLE,
    normal_consistency_mean DOUBLE,
    offset_spread_m DOUBLE,
    offset_std_m DOUBLE,
    source_pixels_median DOUBLE,
    source_pixels_min DOUBLE,
    source_pixels_p10 DOUBLE,
    source_distance_median DOUBLE,
    source_distance_p90 DOUBLE,
    registry_path TEXT
);

CREATE TABLE global_factor_sources (
    workspace_id TEXT,
    site_id TEXT,
    run_id TEXT,
    gid INTEGER,
    key TEXT,
    panoid TEXT,
    local_plane_id INTEGER,
    n_pixels BIGINT,
    d_local DOUBLE,
    d_global DOUBLE,
    nx DOUBLE,
    ny DOUBLE,
    nz DOUBLE,
    class TEXT,
    pano_east_m DOUBLE,
    pano_north_m DOUBLE,
    sources_path TEXT
);

CREATE TABLE local_plane_supports (
    workspace_id TEXT,
    site_id TEXT,
    run_id TEXT,
    panoid TEXT,
    local_plane_id INTEGER,
    cell_count BIGINT,
    bbox_col_min INTEGER,
    bbox_row_min INTEGER,
    bbox_col_max INTEGER,
    bbox_row_max INTEGER,
    centroid_col DOUBLE,
    centroid_row DOUBLE,
    connected_components INTEGER,
    dominant_component_cells BIGINT,
    dominant_component_ratio DOUBLE,
    support_area_px BIGINT,
    mask_path TEXT,
    contour_path TEXT,
    indexmap_path TEXT,
    stage_path TEXT
);

CREATE TABLE local_plane_boundaries_3d (
    workspace_id TEXT,
    site_id TEXT,
    run_id TEXT,
    panoid TEXT,
    local_plane_id INTEGER,
    valid_boundary_points INTEGER,
    centroid_x DOUBLE,
    centroid_y DOUBLE,
    centroid_z DOUBLE,
    bbox_x_min DOUBLE,
    bbox_y_min DOUBLE,
    bbox_z_min DOUBLE,
    bbox_x_max DOUBLE,
    bbox_y_max DOUBLE,
    bbox_z_max DOUBLE,
    area_estimate_m2 DOUBLE,
    distance_min_m DOUBLE,
    distance_median_m DOUBLE,
    distance_max_m DOUBLE,
    boundary_points_path TEXT,
    support_path TEXT,
    status TEXT,
    reason TEXT
);

CREATE TABLE factor_geometries (
    workspace_id TEXT,
    gid INTEGER,
    geometry_type TEXT,
    class TEXT,
    quality TEXT,
    source_count INTEGER,
    unique_pano_count INTEGER,
    centroid_x DOUBLE,
    centroid_y DOUBLE,
    centroid_z DOUBLE,
    bbox_x_min DOUBLE,
    bbox_y_min DOUBLE,
    bbox_z_min DOUBLE,
    bbox_x_max DOUBLE,
    bbox_y_max DOUBLE,
    bbox_z_max DOUBLE,
    extent_major_m DOUBLE,
    extent_minor_m DOUBLE,
    area_estimate_m2 DOUBLE,
    nx DOUBLE,
    ny DOUBLE,
    nz DOUBLE,
    d_global DOUBLE,
    uncertainty_m DOUBLE,
    normal_spread_deg DOUBLE,
    offset_spread_m DOUBLE,
    boundary_spread_m DOUBLE,
    geometry_path TEXT,
    status TEXT
);

CREATE TABLE factor_visibility_candidates (
    workspace_id TEXT,
    gid INTEGER,
    panoid TEXT,
    status TEXT,
    reason TEXT,
    is_observed BOOLEAN,
    expected_visible BOOLEAN,
    distance_m DOUBLE,
    view_angle_deg DOUBLE,
    source_local_plane_id INTEGER,
    source_pixels BIGINT,
    completeness_score DOUBLE,
    occlusion_score DOUBLE,
    visibility_path TEXT
);

CREATE TABLE factor_observation_quality (
    workspace_id TEXT,
    gid INTEGER,
    panoid TEXT,
    local_plane_id INTEGER,
    n_pixels BIGINT,
    completeness_score DOUBLE,
    mask_purity_score DOUBLE,
    view_angle_deg DOUBLE,
    distance_m DOUBLE,
    occlusion_score DOUBLE,
    usable_for_completion BOOLEAN,
    quality_status TEXT,
    support_path TEXT,
    boundary_path TEXT
);

CREATE TABLE temporal_stacks (
    site_id TEXT,
    run_id TEXT,
    workspace_id TEXT,
    batch_id TEXT,
    anchor_panoid TEXT,
    stack_id TEXT,
    stack_status TEXT,
    photometa_count INTEGER,
    stack_dir TEXT,
    source_url TEXT,
    anchor_lat DOUBLE,
    anchor_lng DOUBLE,
    anchor_date TEXT,
    harvested_at TEXT,
    capture_count INTEGER,
    timeline_path TEXT
);

CREATE TABLE temporal_captures (
    site_id TEXT,
    run_id TEXT,
    workspace_id TEXT,
    batch_id TEXT,
    anchor_panoid TEXT,
    stack_id TEXT,
    capture_id TEXT,
    panoid_requested TEXT,
    panoid_returned TEXT,
    date_label TEXT,
    date_short TEXT,
    year_month TEXT,
    is_focal BOOLEAN,
    capture_source TEXT,
    fetched_at TEXT,
    bytes BIGINT,
    capture_dir TEXT,
    meta_path TEXT,
    parsed_path TEXT,
    pointcloud_meta_path TEXT
);

CREATE TABLE temporal_factor_explosion (
    anchor_panoid TEXT,
    stack_id TEXT,
    factor_local_plane_id INTEGER,
    factor_class TEXT,
    factor_pixel_count BIGINT,
    target_east_m DOUBLE,
    target_north_m DOUBLE,
    target_up_m DOUBLE,
    max_match_dist_m DOUBLE,
    n_rows INTEGER,
    n_cols INTEGER,
    grid_path TEXT,
    explosion_3d_path TEXT,
    index_path TEXT,
    viewpoint_index_path TEXT,
    raw_json TEXT
);

CREATE TABLE temporal_factor_cells (
    anchor_panoid TEXT,
    stack_id TEXT,
    row_year_month TEXT,
    year INTEGER,
    month INTEGER,
    col_index INTEGER,
    source_panoid TEXT,
    matched_panoid TEXT,
    matched_distance_m DOUBLE,
    matched_east_m DOUBLE,
    matched_north_m DOUBLE,
    kept BOOLEAN,
    reason TEXT,
    heading_deg DOUBLE,
    pitch_deg DOUBLE,
    roll_deg DOUBLE,
    n_planes INTEGER,
    repair_attempted BOOLEAN,
    used_repaired BOOLEAN,
    repair_status TEXT,
    black_fraction DOUBLE,
    original_black_fraction DOUBLE,
    target_azimuth_deg DOUBLE,
    target_roll_shift_px INTEGER,
    image_path TEXT,
    overlay_path TEXT,
    raw_json TEXT
);

CREATE TABLE temporal_factor_correspondences (
    correspondence_id TEXT,
    workspace_id TEXT,
    gid INTEGER,
    factor_local_plane_id INTEGER,
    anchor_panoid TEXT,
    stack_id TEXT,
    year_month TEXT,
    source_panoid TEXT,
    matched_panoid TEXT,
    transform_json TEXT,
    residual_m DOUBLE,
    residual_px DOUBLE,
    keep BOOLEAN,
    status TEXT,
    reason TEXT,
    crop_path TEXT,
    overlay_path TEXT,
    correspondence_path TEXT
);

CREATE TABLE surface_crops (
    crop_id TEXT,
    workspace_id TEXT,
    gid INTEGER,
    panoid TEXT,
    local_plane_id INTEGER,
    source_type TEXT,
    anchor_panoid TEXT,
    stack_id TEXT,
    year_month TEXT,
    correspondence_id TEXT,
    bbox_col_min INTEGER,
    bbox_row_min INTEGER,
    bbox_col_max INTEGER,
    bbox_row_max INTEGER,
    crop_path TEXT,
    mask_path TEXT,
    support_path TEXT,
    boundary_path TEXT,
    uv_transform_json TEXT,
    projection_json TEXT,
    purity_score DOUBLE,
    completeness_score DOUBLE,
    visibility_status TEXT,
    status TEXT,
    created_at TEXT
);

CREATE TABLE surface_rectified_observations (
    rectified_id TEXT,
    workspace_id TEXT,
    gid INTEGER,
    panoid TEXT,
    local_plane_id INTEGER,
    source_crop_id TEXT,
    rectified_path TEXT,
    mask_path TEXT,
    atlas_json_path TEXT,
    source_crop_path TEXT,
    texture_width INTEGER,
    texture_height INTEGER,
    valid_pixel_count BIGINT,
    valid_fraction DOUBLE,
    source_weight DOUBLE,
    status TEXT,
    created_at TEXT
);

CREATE TABLE surface_stitches (
    stitch_id TEXT,
    workspace_id TEXT,
    gid INTEGER,
    texture_path TEXT,
    contribution_map_path TEXT,
    source_crop_ids TEXT,
    method TEXT,
    source_count INTEGER,
    texture_width INTEGER,
    texture_height INTEGER,
    coverage_score DOUBLE,
    atlas_json_path TEXT,
    preview_path TEXT,
    rectified_stack_path TEXT,
    quality_score DOUBLE,
    completeness_score DOUBLE,
    status TEXT,
    created_at TEXT
);

CREATE TABLE temporal_surface_comparisons (
    comparison_id TEXT,
    workspace_id TEXT,
    gid INTEGER,
    time_a TEXT,
    time_b TEXT,
    source_stitch_id_a TEXT,
    source_stitch_id_b TEXT,
    metric_json TEXT,
    diff_path TEXT,
    report_path TEXT,
    status TEXT,
    created_at TEXT
);
